
args = 1,3

def aaa(args):
    try:
        name, surname, birthday, telephone = args
    except ValueError as exs:
        print (f'Unexpected args{exs}')


aaa(args)